name: Selenium CI with Maven

 on:
   push:
     branches: [ master ]
   pull_request:
     branches: [ master ]

 jobs:
   test:
    runs-on: ubuntu-latest

    env:
      ENV: qa

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Selenium tests
        run: mvn -B -ntp clean test -Denv=qa

      

     
      - name: Zipped TimeStamped ExtentReport
        if: always()
        run: |
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          ZIP_BASE="ExtentReport_$TIMESTAMP"
          ZIP_FNAME="${ZIP_BASE}.zip"
          zip -r "$ZIP_FNAME" Reports/
          echo "ZIP_FNAME=$ZIP_FNAME" >> $GITHUB_ENV
          
      - name: Inspect ZIPs
        if: always()
        run: unzip -l $ZIP_FNAME
        
      - name: Zipped file uploading
        if: always()
        uses: actions/upload-artifact@v4
        with: 
          name: ${{env.ZIP_FNAME}}
          path: ${{env.ZIP_FNAME}}
          
     - name: Deploy to GitHub Pages
       if: always()
       uses: peaceiris/actions-gh-pages@v3
       with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       publish_dir: Reports/
       publish_branch: gh-pages
  
      
      
      
       
        
        
        
        
